// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.0
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery.extend(jQuery.easing,{easeInOutCubic:function(e,f,a,h,g){if((f/=g/2)<1){return h/2*f*f*f+a}return h/2*((f-=2)*f*f+2)+a}});function ws_shift(k,i,c){var d=jQuery;var h=d(this);var b=c.find("li");var f=c.find(".ws_list");var e={position:"absolute",top:0,left:0,width:"100%",height:"100%",overflow:"hidden"};var g=d("<div>").addClass("ws_effect ws_shift").css(e).appendTo(c);var a=d("<div>").css(e).css({display:"none",zIndex:4}).appendTo(g);var j=d("<div>").css(e).css({display:"none",zIndex:3}).appendTo(g);this.go=function(l,p,n){var m=c.width();var o=c.height();a.append(d(i.get(l)).clone());j.append(d(i.get(p)).clone());if(k.responsive<3){a.find("img").css("width","100%");j.find("img").css("width","100%")}f.stop(true,true).hide().css({left:-l+"00%"});var q={left:[{left:-m},{left:0}],right:[{left:m},{left:0}],down:[{top:o},{top:0}],up:[{top:-o},{top:0}]}[k.direction||["left","right","down","up"][Math.floor(Math.random()*4)]];if(k.support.transform){if(q[0].left){q[0]={translate:[q[0].left,0,0]}}else{q[0]={translate:[0,q[0].top,0]}}q[1]={translate:[0,0,0]}}a.show();j.show();wowAnimate(a,q[0],q[1],k.duration,"easeInOutCubic",function(){f.show();a.hide().html("");j.hide().html("");h.trigger("effectEnd")});wowAnimate(j,{scale:1,translate:[0,0,0]},{scale:0.5,translate:[0,0,0]},k.duration,"easeInOutCubic")}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.0
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container20").wowSlider({effect:"shift",prev:"",next:"",duration:12*100,delay:19*100,width:725,height:544,autoPlay:true,autoPlayVideo:false,playPause:true,stopOnHover:false,loop:true,bullets:0,caption:false,captionEffect:"parallax",controls:true,controlsThumb:["data20/images/1.jpg", "data20/images/10.jpg", "data20/images/11.jpg", "data20/images/12.jpg", "data20/images/13.jpg", "data20/images/14.jpg", "data20/images/15.jpg", "data20/images/2.jpg", "data20/images/3.jpg", "data20/images/4.jpg", "data20/images/5.jpg", "data20/images/6.jpg", "data20/images/7.jpg", "data20/images/8.jpg", "data20/images/9.jpg"],responsive:1,fullScreen:false,gestures:1,onBeforeStep:0,images:[{src:"./1.jpg",title:"1"},{src:"./10.jpg",title:"10"},{src:"./11.jpg",title:"11"},{src:"./12.jpg",title:"12"},{src:"./13.jpg",title:"13"},{src:"./14.jpg",title:"14"},{src:"./15.jpg",title:"15"},{src:"./2.jpg",title:"2"},{src:"./3.jpg",title:"3"},{src:"./4.jpg",title:"4"},{src:"./5.jpg",title:"5"},{src:"./6.jpg",title:"6"},{src:"./7.jpg",title:"7"},{src:"./8.jpg",title:"8",href:"http://wowslider.com"},{src:"./9.jpg",title:"9"}]});